shfmt -bn -ci -s -i 4 -w (#812)

diff --git a/e2e-tests/tests/gr-users/04-check-cluster.yaml b/e2e-tests/tests/gr-users/04-check-cluster.yaml
--- a/e2e-tests/tests/gr-users/04-check-cluster.yaml
+++ b/e2e-tests/tests/gr-users/04-check-cluster.yaml
@@ -17,19 +17,19 @@ commands:
       args=""
       set +o errexit
       for user in "${users[@]}"; do
-      	mysql_args="-h $(get_router_service $(get_cluster_name)) -u${user} -p${user}_password_updated"
+          mysql_args="-h $(get_router_service $(get_cluster_name)) -u${user} -p${user}_password_updated"
 
-      	pod=mysql-client
-      	case $user in
-      		heartbeat | xtrabackup)
-      			mysql_args="-h localhost -u${user} -p${user}_password_updated"
-      			pod="$(get_cluster_name)-mysql-0"
-      			;;
-      	esac
+          pod=mysql-client
+          case $user in
+              heartbeat | xtrabackup)
+                  mysql_args="-h localhost -u${user} -p${user}_password_updated"
+                  pod="$(get_cluster_name)-mysql-0"
+                  ;;
+          esac
 
-      	run_mysql "SELECT 1" "${mysql_args}" "${pod}"
+          run_mysql "SELECT 1" "${mysql_args}" "${pod}"
 
-      	args="${args} --from-literal=${user}=$([ $? -eq 0 ] && echo 'success' || echo 'fail')"
+          args="${args} --from-literal=${user}=$([ $? -eq 0 ] && echo 'success' || echo 'fail')"
       done
       set -o errexit
 
