Fix e2e tests.

diff --git a/e2e-tests/tests/config-router/07-check-config.yaml b/e2e-tests/tests/config-router/07-check-config.yaml
--- a/e2e-tests/tests/config-router/07-check-config.yaml
+++ b/e2e-tests/tests/config-router/07-check-config.yaml
@@ -7,8 +7,11 @@ commands:
 
       source ../../functions
 
-      pod=$(kubectl get pod --no-headers --selector=app.kubernetes.io/component=router | awk '{print $1}' | head -n 1)
+      pod=$(get_router_pods | head -n 1)
 
-      if ! kubectl exec -it $pod  -- bash -c 'cat /tmp/router/log/mysqlrouter.log' | grep -q 'DEBUG' ; then
+      echo "$pod"
+
+      if ! kubectl -n "${NAMESPACE}" exec -it $pod -- bash -c 'cat /tmp/router/log/mysqlrouter.log' | grep -q 'DEBUG' ; then
+        echo "Failed to find necessary logs in $pod, expected logs in /tmp/router/log/mysqlrouter.log"
         exit 1
       fi
