K8SPS-393

diff --git a/e2e-tests/functions b/e2e-tests/functions
--- a/e2e-tests/functions
+++ b/e2e-tests/functions
@@ -96,7 +96,16 @@ deploy_pmm_server() {
 		local additional_params="--set platform=openshift --set sa=pmm-server --set supresshttp2=false"
 	fi
 
-	helm install monitoring -n "${NAMESPACE}" --set imageTag=${IMAGE_PMM_SERVER#*:} --set imageRepo=${IMAGE_PMM_SERVER%:*} $additional_params https://percona-charts.storage.googleapis.com/pmm-server-$PMM_SERVER_VERSION.tgz
+  kubectl delete clusterrole monitoring --ignore-not-found
+  kubectl delete clusterrolebinding monitoring --ignore-not-found
+
+  helm install monitoring percona/pmm -n "${NAMESPACE}" \
+      --set fullnameOverride=monitoring \
+      --version ${PMM_SERVER_VERSION} \
+      --set imageTag=${IMAGE_PMM_SERVER#*:} \
+      --set imageRepo=${IMAGE_PMM_SERVER%:*} \
+      --set service.type=LoadBalancer \
+      --force
 
 	until kubectl -n "${NAMESPACE}" exec monitoring-0 -- bash -c "ls -l /proc/*/exe 2>/dev/null| grep postgres >/dev/null"; do
 		echo "Retry $retry"
@@ -110,15 +119,37 @@ deploy_pmm_server() {
 }
 
 get_pmm_api_key() {
-	local key_name=$1
+    local key_name=$1
 
-	if [[ -z $key_name ]]; then
-		key_name="operator"
-	fi
+    if [[ -z $key_name ]]; then
+        key_name="operator"
+    fi
 
-	local ADMIN_PASSWORD
-	ADMIN_PASSWORD=$(kubectl -n "${NAMESPACE}" exec monitoring-0 -- bash -c "printenv | grep ADMIN_PASSWORD | cut -d '=' -f2")
-	curl --insecure -X POST -H "Content-Type: application/json" -d "{\"name\":\"$key_name\", \"role\": \"Admin\"}" "https://admin:$ADMIN_PASSWORD@$(get_service_ip monitoring-service)/graph/api/auth/keys" | jq .key
+    local ADMIN_PASSWORD
+    ADMIN_PASSWORD=$(kubectl -n "${NAMESPACE}" get secret pmm-secret -o jsonpath="{.data.PMM_ADMIN_PASSWORD}" | base64 --decode)
+
+    if [[ -z $ADMIN_PASSWORD ]]; then
+        echo "Error: ADMIN_PASSWORD is empty or not found!" >&2
+        return 1
+    fi
+
+    local response status_code json_response
+    response=$(curl --insecure -s -X POST -H 'Content-Type: application/json' \
+        -d "{\"name\":\"${key_name}\", \"role\": \"Admin\"}" \
+        --user "admin:${ADMIN_PASSWORD}" \
+        "https://$(get_service_ip monitoring-service)/graph/api/auth/keys" \
+        -w "\n%{http_code}")
+
+    status_code=$(echo "$response" | tail -n1)
+    json_response=$(echo "$response" | sed '$ d')
+
+    if [[ "$status_code" -eq 200 ]]; then
+        echo "$json_response" | jq -r '.key'
+    else
+        echo "Error: Failed to get API key with HTTP status code: $status_code)" >&2
+        echo "Response: $json_response" >&2
+        return 1
+    fi
 }
 
 delete_pmm_api_key() {
