fix monitoring test

diff --git a/e2e-tests/functions b/e2e-tests/functions
--- a/e2e-tests/functions
+++ b/e2e-tests/functions
@@ -38,6 +38,19 @@ deploy_pmm_server() {
 			--set platform="${platform}" \
 			"https://percona-charts.storage.googleapis.com/pmm-server-${PMM_SERVER_VERSION}.tgz"
 	fi
+	SERVICE="postgres"
+  until kubectl -n "${NAMESPACE}" exec monitoring-0 -- bash -c "pgrep -x $SERVICE >/dev/null"; do
+    echo "Retry $retry"
+    sleep 5
+    let retry+=1
+    if [ $retry -ge 20 ]; then
+      echo "Max retry count $retry reached. Pmm-server can't start"
+      exit 1
+    fi
+  done
+  ADMIN_PASSWORD=$(kubectl -n "${NAMESPACE}" exec monitoring-0 -- bash -c "printenv | grep ADMIN_PASSWORD | cut -d '=' -f2")
+  kubectl exec -n "${NAMESPACE}" monitoring-0 -- bash -c "grafana-cli --homepath=/usr/share/grafana --config=/etc/grafana/grafana.ini admin reset-admin-password $ADMIN_PASSWORD"
+
 }
 
 get_operator_pod() {
