add `self-healin-chaos` test

diff --git a/e2e-tests/functions b/e2e-tests/functions
--- a/e2e-tests/functions
+++ b/e2e-tests/functions
@@ -459,3 +459,53 @@ verify_certificate_sans() {
 
 	diff "${have}" "${want}"
 }
+
+deploy_chaos_mesh() {
+	local chaos_mesh_ns=$1
+
+	destroy_chaos_mesh
+
+	helm repo add chaos-mesh https://charts.chaos-mesh.org
+	helm install chaos-mesh chaos-mesh/chaos-mesh --namespace="${chaos_mesh_ns}" --set chaosDaemon.runtime=containerd --set chaosDaemon.socketPath=/run/containerd/containerd.sock --set dashboard.create=false --version 2.5.1
+	sleep 10
+}
+
+destroy_chaos_mesh() {
+	local chaos_mesh_ns
+	chaos_mesh_ns=$(helm list --all-namespaces --filter chaos-mesh | tail -n1 | awk -F' ' '{print $2}' | sed 's/NAMESPACE//')
+
+	if [ -n "${chaos_mesh_ns}" ]; then
+		helm uninstall chaos-mesh --namespace "${chaos_mesh_ns}" || :
+	fi
+
+	for i in $(kubectl api-resources | grep chaos-mesh | awk '{print $1}'); do delete_resource_with_finalizer "${i}" --all; done
+	for i in $(kubectl get crd -A | grep 'chaos-mesh.org' | awk '{print $1}'); do delete_resource_with_finalizer crd "${i}"; done
+	for i in $(kubectl get clusterrolebinding -A | grep 'chaos-mesh' | awk '{print $1}'); do delete_resource_with_finalizer clusterrolebinding "${i}"; done
+	for i in $(kubectl get clusterrole -A | grep 'chaos-mesh' | awk '{print $1}'); do delete_resource_with_finalizer clusterrole "${i}"; done
+	for i in $(kubectl get mutatingwebhookconfiguration -A | grep 'chaos-mesh' | awk '{print $1}'); do delete_resource_with_finalizer mutatingwebhookconfiguration "${i}"; done
+	for i in $(kubectl get validatingwebhookconfiguration -A | grep 'chaos-mesh' | awk '{print $1}'); do delete_resource_with_finalizer validatingwebhookconfiguration "${i}"; done
+	for i in $(kubectl get validatingwebhookconfiguration -A | grep 'validate-auth' | awk '{print $1}'); do delete_resource_with_finalizer validatingwebhookconfiguration "${i}"; done
+}
+
+delete_resource_with_finalizer() {
+
+	local resource=$1
+	local name=$2
+
+	if [ "$name" == "--all" ]; then
+		for i in $(kubectl get "${resource}" | grep -v NAME | awk '{print $1}'); do
+			delete_resource_with_finalizer "${resource}" "${i}"
+		done
+		return
+	fi
+
+	timeout 30 kubectl patch "${resource}" "${name}" -p '{"metadata":{"finalizers":[]}}' --type=merge
+	set +e
+	timeout 30 kubectl delete "${resource}" "${name}"
+	# if exit status is 124 (timeout exit code), then apply patch again and delete
+	if [ $? -eq 124 ]; then
+		timeout 30 kubectl patch "${resource}" "${name}" -p '{"metadata":{"finalizers":[]}}' --type=merge
+		timeout 30 kubectl delete "${resource}" "${name}"
+	fi
+	set -e
+}
